const projects = [
  {name:'Remem',repo:'remem',category:'AGENT MEMORY',groups:['memory'],tags:['Python','Memory API','Semantic retrieval'],description:'Persistent memory for AI agents. Store what an agent learns and retrieve useful context across sessions.',problem:'Agents lose useful user context between sessions, forcing people to repeat themselves.',approach:'A memory API handles embeddings, storage, retrieval, and ranking. Hybrid scoring combines semantic relevance, recency, and importance, with a score breakdown for each result.',output:'A Python client with remember, recall, and context methods for adding memory to agent applications.'},
  {name:'IntegrationOS',repo:'IntegrationOS',category:'MULTI-AGENT WORKFLOW',groups:['agents'],tags:['Python','LangGraph','Pydantic','API integration'],description:'An experimental API onboarding pipeline that turns a documentation URL into a plan, SDK stub, and integration guide.',problem:'Moving from API documentation to a usable integration involves research, planning, testing, and writing.',approach:'A LangGraph workflow coordinates research, planning, task dispatch, executor agents, and a reviewer. Independent tasks can run in parallel.',output:'An SDK stub, an integration guide, and structured task results. This is a prototype; runtime validation depends on configured services and model credentials.'},
  {name:'Owed',repo:'owed--credit-memory-agent',category:'AI APPLICATION',groups:['agents','apps'],tags:['React','Supabase','Deno','LLM integration'],description:'A credit memory agent that uses customer payment history to assess risk and suggest practical follow-up actions.',problem:'Small businesses need a consistent way to understand outstanding customer credit and changing payment behavior.',approach:'A customer ledger feeds an LLM assessment with explanations and recommended next steps. A rule-based fallback supports operation when the AI call is unavailable.',output:'Customer assessments, a risk-prioritized dashboard, CSV imports, and suggested follow-up messages.'},
  {name:'Research Agent',repo:'Research-agent',category:'MULTI-AGENT RESEARCH',groups:['agents'],tags:['LangGraph','Gemini','Tavily','LangSmith'],description:'A coordinated research, analysis, and writing workflow that turns a question into a structured article.',problem:'Producing an article from web research involves several distinct stages with different responsibilities.',approach:'Research, analyzer, and writer agents work under an orchestrator that selects the required stages. Tavily supports web search and LangSmith supports tracing.',output:'Research findings, analysis, and a generated article, with caching and memory components described in the repository.'},
  {name:'RAG Assistance',repo:'RAG-Assistance',category:'KNOWLEDGE RETRIEVAL',groups:['memory','apps'],tags:['Python','LangChain','Vector search','Supabase'],description:'An AI research assistant designed to answer AI-related questions using retrieved knowledge and conversation context.',problem:'A useful subject-specific assistant needs relevant reference information and continuity across conversations.',approach:'Semantic retrieval brings knowledge-base context into a LangChain generation pipeline, alongside Supabase-backed conversation memory.',output:'Context-aware answers about AI topics. Retrieval supports grounding; generated answers still need evaluation.'},
  {name:'AI Question Generator',repo:'AI-Question-Generator',category:'DOCUMENT AUTOMATION',groups:['apps'],tags:['Gemini','Apify','Document processing'],description:'An Apify Actor that turns documents into educational questions with configurable formats and difficulty.',problem:'Creating varied educational questions from source documents takes repetitive reading and formatting work.',approach:'Gemini analyzes content from PDF, DOCX, TXT, and Markdown documents. Users configure question types, quantity, difficulty, and export format.',output:'Multiple-choice, true/false, essay, and fill-in-the-blank questions exported as JSON, CSV, or Moodle XML.'},
  {name:'Reflect AI',repo:'Reflet_ai',category:'PLANNING PROTOTYPE',groups:['apps'],tags:['JavaScript','Node.js','Google OAuth','Local storage'],description:'A personal goal planner that turns a deadline into daily actions and supports weekly, monthly, and end-of-goal reflections.',problem:'A time-bound goal needs a realistic plan, a clear view of today’s actions, and a way to learn from progress.',approach:'Editable planning templates and capacity-aware scheduling organize checkpoints and actions around workdays and a daily time budget. A reflection journal connects lessons to the next action.',output:'Daily action tracking, progress and streaks, reflection journals, and export/import backups. This prototype uses templates rather than a remote language model; data stays in browser storage, without cross-device sync.'}
];
const grid=document.querySelector('#projects');
function render(filter='all'){
 const shown=projects.filter(p=>filter==='all'||p.groups.includes(filter));
 grid.innerHTML=shown.map(p=>`<article class="project" data-repo="${p.repo}"><div class="project-top"><span class="project-num">${String(projects.indexOf(p)+1).padStart(2,'0')}</span><span class="project-category">${p.category}</span></div><div class="project-body"><h3>${p.name}</h3><p>${p.description}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div></div><div class="project-links"><button data-project="${p.repo}">Read project overview</button><a href="https://github.com/Sunvic567/${p.repo}" target="_blank" rel="noopener noreferrer">View source</a></div></article>`).join('');
 document.querySelector('#results').textContent=`${shown.length} projects shown`;
}
document.querySelector('[data-filter="all"] span').textContent=projects.length;
render();
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});render(b.dataset.filter)}));
document.querySelectorAll('nav a[href^="#"]').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('nav a').forEach(a=>a.removeAttribute('aria-current'));link.setAttribute('aria-current','location')}));
const dialog=document.querySelector('#detail');
grid.addEventListener('click',e=>{const button=e.target.closest('[data-project]');if(!button)return;const p=projects.find(p=>p.repo===button.dataset.project);document.querySelector('#detail-content').innerHTML=`<p class="eyebrow">${p.category}</p><h2 id="dialog-title">${p.name}</h2><h3>The problem</h3><p>${p.problem}</p><h3>The approach</h3><p>${p.approach}</p><h3>The output</h3><p>${p.output}</p><div class="tags">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><div class="actions"><a class="button primary" href="https://github.com/Sunvic567/${p.repo}" target="_blank" rel="noopener noreferrer">Explore the repository</a></div>`;dialog.setAttribute('aria-labelledby','dialog-title');dialog.showModal()});
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
document.querySelector('#copy-email').addEventListener('click',async()=>{const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText('sunvictor567@gmail.com');status.textContent='Email address copied.'}catch{status.textContent='Copy this address: sunvictor567@gmail.com'}});
document.querySelector('#year').textContent=new Date().getFullYear();
